#include "stdafx.h"
#include <string>
#include <hash_map>
using namespace std;


//https://leetcode-cn.com/problems/remove-duplicates-from-sorted-list/
//Author : ºÎ»¶
//Date   : 2019-04-15

/*
Given two strings s and t which consist of only lowercase letters.

	String t is generated by random shuffling string s and then add one more letter at a random position.

	Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

class Solution {
public:
	char findTheDifference(string s, string t) {

		int tLen = t.length();
		std::hash_map<char,int> hash;
		for (int i = 0; i < tLen; i++){
			hash.insert()

		}

	}
};

int _tmain(int argc, _TCHAR* argv[]){

	Solution sln;
	sln.isValid("((");
	return 0;
}